message: Add RevaultMessage enum to contain all message types and imp…
revault/revault_net pull request #46
Opened 2021-03-10 19:11 UTC by JSwambo

…licitly create json_wrapper

The JSON serialized message format is based on ["internally tagged"](https://serde.rs/enum-representations.html) enum representation:
`{
    "type": "message_name",
    "param1": ...,
    "param2": ...,
    ....
}`

An alternative design would use ["externally tagged"](https://serde.rs/enum-representations.html) enum representation:
`{
    "message_name": {
    "param1": ...,
    "param2": ...,
    ....
    }
}`

Fixes #24

2021-03-11 22:07 UTC, darosior reviewed
Nice, there are a few discrepancies with practical-revault though

2021-03-11 22:07 UTC, darosior commented on src/message.rs
> +    SigToWatchtower(watchtower::Sig),
As such it would serialize the `method` field value as being the enum variant name, which does not conform to practical-revault.

Example for the `SetSpendTx` variant:
```
'{"type":"SetSpendTx","deposit_outpoint":"6e4977728e7100db80c30751f27cf834b7a1e02d083a4338874e48d1f3694446:0","transaction":[2,0,0,0,1,142,248,71,188,159,42,54,26,182,63,122,190,142,86,195,105,209,94,115,11,168,150,116,176,155,66,103,75,212,12,148,245,0,0,0,0,0,205,86,0,0,2,128,216,1,0,0,0,0,0,34,0,32,174,27,222,227,136,242,19,96,84,121,114,39,177,74,152,61,40,222,41,245,34,243,235,220,78,37,253,43,174,61,158,82,1,0,0,0,0,0,0,0,0,0,0,0,0]}'
```
Whereas it should be:
```
'{"method":"set_spend_tx","deposit_outpoint":"6e4977728e7100db80c30751f27cf834b7a1e02d083a4338874e48d1f3694446:0","transaction":[2,0,0,0,1,142,248,71,188,159,42,54,26,182,63,122,190,142,86,195,105,209,94,115,11,168,150,116,176,155,66,103,75,212,12,148,245,0,0,0,0,0,205,86,0,0,2,128,216,1,0,0,0,0,0,34,0,32,174,27,222,227,136,242,19,96,84,121,114,39,177,74,152,61,40,222,41,245,34,243,235,220,78,37,253,43,174,61,158,82,1,0,0,0,0,0,0,0,0,0,0,0,0]}'
```
(Don't mind the tx serialization as an array which is another violation of practical-revault which is outside the scope of this PR...)


You should add a serde proc macro so that each enum variant serializes to the corresponding method name in practical-revault.

2021-03-11 22:07 UTC, darosior commented on src/message.rs
> +        }
This is repeating all along the tests, could you make this a macro like the `roundtrip!` one? Or actually extend `roundtrip!`

2021-03-11 22:07 UTC, darosior commented on src/message.rs
> +        }
Ah also, try `assert!(matches!(Variant(_), serde_json::from_slice::<RevaultMessage>(&serialized_msg).unwrap()))` :)

2021-03-12 09:02 UTC, darosior commented
Ok, i've opened https://github.com/revault/revault_net/pull/47 with a fix for the serialization of transactions and tests for the representation. So you can just rebase on top of it (if it's correct :p) so you don't have to do it again there, just to add the new fields.

2021-03-12 12:23 UTC, JSwambo commented on src/message.rs
> +        }
> This is repeating all along the tests, could you make this a macro like the `roundtrip!` one? Or actually extend `roundtrip!`

How do you match against an enum variant? I have this, it compiles, but when I try and use it I get some errors:


    macro_rules! assert_revault_message_serde {

        ($msg:ident, $enum_pattern: pat) => {
        
            let serialized_msg = serde_json::to_vec(&$enum_pattern($msg)).unwrap();
            
            let _deserialized_msg =
            
                serde_json::from_slice::<RevaultMessage>(&serialized_msg).unwrap();
                
            assert!(matches!($enum_pattern, _deserialized_msg));
            
I think the token type is wrong, but I can't find one that would work (pat, expr, stmt, ident,...??). To use it I tried:

    assert_revault_message_serde!(msg, RevaultMessage::SigAck(_))
    
 
And got: 

    error: expected expression, found `RevaultMessage::SigAck(_)`
    --> src/message.rs:275:54
    |
    275 |             let serialized_msg = serde_json::to_vec(&$enum_pattern($msg)).unwrap();
    |                                                      ^^^^^^^^^^^^^ expected expression
    ...
    319 |         assert_revault_message_serde!(msg, RevaultMessage::SigAck(_));
    |         -------------------------------------------------------------- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

2021-03-12 12:39 UTC, darosior commented on src/message.rs
> +        }
Hehe, muh meta programming :p

I think there you want to take an `ident` (if not fallback to `expr`), so:
```rust
macro_rules! roundtrip_message_enum {
    ($msg:ident, $enum_variant:ident) => {
        let serialized_msg = serde_json::to_vec(&$enum_variant($msg)).unwrap();
        let deserialized_msg: RevaultMessage = serde_json::from_slice(&serialized_msg).unwrap();
        
        assert!(matches!($enum_variant(_), deserialized_msg));
    }
}
```
Which you would use as
```rust
roundtrip_message_enum!(msg, RevaultMessage::SigAck);
```

Not sure it compiles though, didn't test. But i think it should work

2021-03-12 12:39 UTC, darosior commented on src/message.rs
> +        }
Or maybe `pat` works, i don't know

2021-03-12 13:34 UTC, darosior commented
Sorry for the conflict, but the resolution should be trivial.

2021-03-14 12:33 UTC, JSwambo commented on src/message.rs
> +    SigToWatchtower(watchtower::Sig),
Right. So now I've put `#[serde(tag = "method", content = "params")]` for the enum and`#[serde(rename = "practical_revault_name")]` with each variant. This is closer to practical-revault, but it's only correct for the method messages ("sig", "request_spend", "get_spend_tx", "get_sigs", "sign"). The result messages  (the rest) have a different structure. So I'm wondering if there should be two enums instead, one for methods and another for results? 

Another small detail, using the same method name for SigToWatchtower and SigToServer results in failed rountrip test for the SigToServer as it attempts to deserialize into SigToWatchtower.

2021-03-15 05:50 UTC, darosior commented on src/message.rs
> +    SigToWatchtower(watchtower::Sig),
> The result messages (the rest) have a different structure. So I'm wondering if there should be two enums instead, one for methods and another for results?

I think you are right that we need to identify requests in the enum. However i'm not sure we should use an enum for the results, we only want them to share this specific serialization. Maybe we could have a
```
#[serde(content = "params")]
```
On top of each response ?

2021-03-15 11:25 UTC, JSwambo commented on src/message.rs
> +    SigToWatchtower(watchtower::Sig),
> ```
> #[serde(content = "result")]
> ```
> On top of each response ?

It's not a valid variant attribute, it only applies to the whole enum. If we had a separate enum we could get the correct formatting. But I'm not sure if `RevaultMethodMessage` and `RevaultResultMessage` simplifies stuff or complicates it. When do you expect to do be de/serializing from/to JSON?

2021-03-15 20:04 UTC, darosior commented on src/message.rs
> +    SigToWatchtower(watchtower::Sig),
> It's not a valid variant attribute, it only applies to the whole enum.

I don't mean it for enum variants but for response structs. ie have an enum for requests where you match on unknown incoming messages, for responses you don't need an enum as you know what you'll be receiving

2021-03-16 11:50 UTC, JSwambo commented on src/message.rs
> +    SigToWatchtower(watchtower::Sig),
Ah I get you now. Still, `#[serde(content = "...")]` only works for enums. Instead I created a `Response` struct to wrap the response messages (see the latest update). Again, I'm not sure when you expect to be de/serializing from/into JSON (debugging/ logging?). It's a little clunky to use. For example, you need

`let msg = Response { result: server::SigAck {...} }` 

WDYT? Should I add some conversion functions e.g. `server::SigAck::into_response()`?

2021-03-22 20:14 UTC, darosior reviewed
As mentioned privately i'm still unsure about the `id`. Theoretically we should have it but in practice.. We don't need it.

2021-03-22 20:14 UTC, darosior commented on src/message.rs
> +    impl RevaultRequest for Sig {}
I think these traits are unnecessary

2021-03-22 20:14 UTC, darosior commented on src/message.rs
> +    pub id: Option<u32>,
Why is it an Option? This opens up the possibility for it being null and us unwraping it while there is no need ?

2021-03-22 20:14 UTC, darosior commented on src/message.rs
> +            id: None,
It's neat, but conceptually i think the `id` should never be None. Unfortunately this makes the implem moot

2021-03-24 12:59 UTC, JSwambo commented on src/message.rs
> +    impl RevaultRequest for Sig {}
Their purpose is to enforce at compile time that only types that impl RevaultRequest are used as params for Requests (similarly with RevaultResponse). If that's not helpful, I'll remove?

2021-03-24 13:03 UTC, JSwambo commented
> As mentioned privately i'm still unsure about the `id`. Theoretically we should have it but in practice.. We don't need it.

Ok. Do we really need it (even theoretically) if all per-channel communication is synchronous?

2021-03-24 13:15 UTC, darosior commented on src/message.rs
> +    impl RevaultRequest for Sig {}
Yeah but why do you want to enforce that ? If as an user of the lib i want to pass my type to Requests, it's not preventing me to do so ? (just a one line change)

2021-03-26 11:39 UTC, JSwambo commented on src/message.rs
> +    impl RevaultRequest for Sig {}
I was just considering safety for a user, not security from a user. Anyway, I've removed in the latest version

2021-03-26 14:04 UTC, JSwambo commented
Updated version has no 'id' and no unnecessary traits. Also rebased on #50

2021-04-18 15:28 UTC, darosior commented
Rebased on master :)

2021-04-18 16:17 UTC, darosior requested changes
Working on a fixup commit for this and introducing some other modifications that are mainly nits.

2021-04-18 16:17 UTC, darosior commented on src/message.rs
> +}
This one is a typo in practical-revault, obviously `SetSpendTx != 'request_spend'` !!

2021-04-18 16:26 UTC, darosior commented on src/message.rs
> +            r#"{"method":"request_spend","params":{"deposit_outpoints":["6e4977728e7100db80c30751f27cf834b7a1e02d083a4338874e48d1f3694446:0"],"transaction":"020000000001042a9eb96ed62b3a35883fe632def8
You even tested it.... :sob: Like seriously.

2021-04-18 16:35 UTC, darosior approved these changes
ACK d5a5bec

2021-04-20 22:55 UTC, darosior commented
I'm going to go ahead and merge this. After #55 i'm convinced it was a good step forward and as such it does not change message serialization, therefore it's fine to land it in master (as in it won't break the demo right away).

2021-04-20 22:55 UTC, merged

2021-04-22 13:46 UTC, darosior commented
I was wrong, it was a breaking change..